" --- PLUGINS ---
call plug#begin('~/.vim/plugged')

" IntelliSense
Plug 'neoclide/coc.nvim', {'branch': 'release'}

" File Explorer
Plug 'preservim/nerdtree'

" Status bar
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" Fuzzy Finder
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

" THEME: Nord
Plug 'arcticicestudio/nord-vim'

call plug#end()


" --- VISUAL SETTINGS (SAFE MODE) ---
syntax on
set background=dark

" Enable True Color (Essential for your terminal)
if (has("termguicolors"))
  set termguicolors
endif

" Safely try to load the theme. If not installed yet, it won't crash.
try
  colorscheme nord
  let g:airline_theme='nord'
catch /^Vim\%((\a\+)\)\=:E185/
  " Fallback if Nord is missing (e.g., first install)
  colorscheme default
endtry


" --- BASIC SETTINGS ---
set number
set relativenumber
set expandtab
set shiftwidth=4
set tabstop=4
set smartindent
set mouse=a
set cursorline
set scrolloff=8


" --- COC CONFIGURATION ---
inoremap <silent><expr> <TAB>
      \ coc#pum#visible() ? coc#pum#next(1) :
      \ CheckBackspace() ? "\<Tab>" :
      \ coc#refresh()
inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm() : "\<CR>"

nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

nnoremap <silent> K :call ShowDocumentation()<CR>

function! ShowDocumentation()
  if CocAction('hasProvider', 'hover')
    call CocActionAsync('doHover')
  else
    call feedkeys('K', 'in')
  endif
endfunction

function! CheckBackspace() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction
